project_name: terraform-credentials-gcs

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -X 'github.com/SkYNewZ/terraform-credentials-gcs/cmd.version={{.Version}}' -X "github.com/SkYNewZ/terraform-credentials-gcs/cmd.commit={{.Commit}}" -X 'github.com/SkYNewZ/terraform-credentials-gcs/cmd.date={{.Date}}'

archives:
  - replacements:
      amd64: x86_64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
